### ISSUE TITLE
Create Logging API's

### ISSUE THREAD

**Issue by nesh170** [nesh170/asap-inventory-system#102]
API calls

 1. getAllLogs()
	 - Filter support for user, item and timestamp
	 - Gets all the logs 
	 - Timestamp using a datetime calendar widget
 2. getDetailedLog(log_id)
	 - Get the complete log for that item

ActionEnum

 - Contains each of the action as an enum so it would be easier to use the log utility

Log Utility

 - log(str initiating_username, arr[item_id] item_involved, ActionEnum action, str effected_username=None)
 
This function takes in the parameter and creates a log entry on the log table appropriately.

**Comment by ankitkayastha** [comment]
https://github.com/nesh170/asap-inventory-system/pull/122
