### ISSUE TITLE
Delete receiver of disbursement and it then shows null

### ISSUE THREAD

**Issue by ankitkayastha** [nesh170/asap-inventory-system#136]
If the receiver of a disbursement is deleted (user deleted), then the disbursement corresponding to that receiver has null fields, even though it should be deleted. It's odd because the model has on on_delete=models.CASCADE, but receiver also has null=True, and blank=True, so not sure if that could have an effect on the behavior.

**Comment by nesh170** [comment]
An unactive disbursement is tracked based on receiver!=None. This is intended behavior so it is fine
