### ISSUE TITLE
Returning Loaned Item

### ISSUE THREAD

**Issue by ankitkayastha** [nesh170/asap-inventory-system#196]
When returning a loaned item, I had 3 transistors loaned out to me. I specified 1 transistor was returned (of the 3). However, when I get all loans, the item quantity seems to update correctly, but the loan quantity does not seem to update in the serializer (still says 3). 

Regarding the response of the returnItem API Call, the JSON item quantity seems to have the old value of the quantity, not the updated one. And the quantity field that represents the quantity loaned out is not updated (still says 3).

**Comment by nesh170** [comment]
https://github.com/nesh170/asap-inventory-system/pull/201

should fix it. CLOSE if fixed :D
