### ISSUE TITLE
Intersection of Backfill and Assets

### ISSUE THREAD

**Issue by ankitkayastha** [nesh170/asap-inventory-system#244]
When a backfill is marked satisfied, let's say it completely satisfies the loan thus removing the loan from the system (converting it to a disbursement). In this case, if the loan has specific assets, these assets will also have to be converted to a disbursement.

**Comment by ankitkayastha** [comment]
Have to make everything asset friendly. Such as satisfying a loan - when removing some quantity from a loan, have to remove those specific assets

**Comment by nesh170** [comment]
Rip life :/
