### ISSUE TITLE
Satisfy/Failing backfills when cart is approved

### ISSUE THREAD

**Issue by ankitkayastha** [nesh170/asap-inventory-system#265]
Should you be able to mark a backfill as failed or satisfied when the cart is approved but not fulfilled? Essentially the items have arrived before the user has actually gotten the items

**Comment by nesh170** [comment]
nah :/

**Comment by nesh170** [comment]
We are leaving it to run Satisfy/Failing backfills when cart is approved since this is already implemented in the system :D wee
