### ISSUE TITLE
Implement OAuth2 Support

### ISSUE THREAD

**Issue by andrewssun1** [nesh170/asap-inventory-system#28]

**Comment by nesh170** [comment]
1) --login (http://localhost:8000/o/token/)
POST /o/token/ HTTP/1.1
Host: localhost:8000
Content-Type: application/x-www-form-urlencoded
Cache-Control: no-cache

grant_type=password&username=<username>&client_id=<client_id>&password=<pass>

Response:
{
  "access_token": "9LlAjIfOf29qZ1E8YeZHWV4dJth8TR",
  "expires_in": 36000,
  "token_type": "Bearer",
  "scope": "read write groups",
  "refresh_token": "jGB3GGptGdw3vcTgBUZ7NTaBP1p31b"
}

2) --logout ()

POST /o/revoke_token/ HTTP/1.1
Host: localhost:8000
Content-Type: application/x-www-form-urlencoded
Cache-Control: no-cache

token=<token>&client_id=<client_id>

3) To Post or get an item, make sure there is a bearer
POST /item/ HTTP/1.1
Host: localhost:8000
Content-Type: application/json
Authorization: Bearer <access_token>
Cache-Control: no-cache

{
	"name": "Ankit Devices",
    "quantity": 10,
    "tags": [{"tag":"hello"}]
}

**Comment by nesh170** [comment]
PR Done

https://github.com/nesh170/asap-inventory-system/pull/45
