### ISSUE TITLE
Creating CRUD Request API

### ISSUE THREAD

**Issue by nesh170** [nesh170/asap-inventory-system#31]

**Comment by ankitkayastha** [comment]
Here are the JSON representations for the API Calls (as well as their URLs):

**POST: /api/request/**
**Request Body:**
{
	"item_id" : 3,
	"reason": "testing create request for nexus",
	"quantity":2
}
**Response Body:**
{
  "id": 43,
  "owner": {
    "id": 1,
    "username": "admin",
    "email": "test@test.com",
    "is_staff": true,
    "last_login": "2017-02-06T06:33:47.593515Z",
    "date_joined": "2017-02-01T04:02:40.863803Z"
  },
  "status": "outstanding",
  "item": {
    "id": 46,
    "name": "Flamethrower1245",
    "quantity": 3
  },
  "item_id": 46,
  "quantity": 5,
  "reason": "creating more requests for flamethrower pls",
  "timestamp": "2017-02-06T21:02:01.646221Z",
  "admin_timestamp": null,
  "admin_comment": null,
  "admin": null
}
**GET: /api/request/**
**Response Body:**
{
  "count": 34,
  "next": "http://localhost:8000/api/request/?page=2",
  "previous": null,
  "results": [
    {
      "id": 35,
      "owner": {
        "id": 1,
        "username": "admin",
        "email": "test@test.com",
        "is_staff": true,
        "last_login": "2017-02-06T06:33:47.593515Z",
        "date_joined": "2017-02-01T04:02:40.863803Z"
      },
      "status": "outstanding",
      "item": {
        "id": 46,
        "name": "Flamethrower1245",
        "quantity": 3
      },
      "item_id": 46,
      "quantity": 1,
      "reason": "This girl is on fire",
      "timestamp": "2017-02-06T18:50:12.105139Z",
      "admin_timestamp": null,
      "admin_comment": null,
      "admin": null
    },
    {
      "id": 38,
      "owner": {
        "id": 1,
        "username": "admin",
        "email": "test@test.com",
        "is_staff": true,
        "last_login": "2017-02-06T06:33:47.593515Z",
        "date_joined": "2017-02-01T04:02:40.863803Z"
      },
      "status": "outstanding",
      "item": {
        "id": 46,
        "name": "Flamethrower1245",
        "quantity": 3
      },
      "item_id": 46,
      "quantity": 1,
      "reason": "this is lit",
      "timestamp": "2017-02-06T18:50:53.011142Z",
      "admin_timestamp": null,
      "admin_comment": null,
      "admin": null
    },
...continues on for however many requests there are
**GET: /api/request/detailed/{pk}/**
**Response Body:**
{
  "id": 43,
  "owner": {
    "id": 1,
    "username": "admin",
    "email": "test@test.com",
    "is_staff": true,
    "last_login": "2017-02-06T06:33:47.593515Z",
    "date_joined": "2017-02-01T04:02:40.863803Z"
  },
  "status": "outstanding",
  "item": {
    "id": 46,
    "name": "Flamethrower1245",
    "quantity": 3
  },
  "item_id": 46,
  "quantity": 5,
  "reason": "creating more requests for flamethrower pls",
  "timestamp": "2017-02-06T21:02:01.646221Z",
  "admin_timestamp": null,
  "admin_comment": null,
  "admin": null
}
**POST: /api/request/disburse/**
**Request Body:**
{
	"item_id" : 3,
	"quantity" : 1,
	"receiver" : "ankit",
	"disburse_comment" : "this should disburse and also log"
}
**Response Body:**
{
  "item_id": 3,
  "quantity": 1,
  "receiver": "ankit",
  "disburse_comment": "this should disburse and also log"
}
**PATCH: /api/request/approve/{pk}/**
Note: status field of request is updated automatically on backend
**Request Body:**
{
	"id" : 4,
	"admin_comment": "testing approve request this should work"
}
**Response Body:**
{
  "id": 4,
  "admin_comment": "testing approve request this should work",
  "admin_timestamp": "2017-02-03T16:45:08.672113",
  "admin": 1
}
**PATCH: /api/request/deny/{pk}/**
Note: status field of request is updated automatically on backend
**Request Body:**
{
	"id" : 1,
	"admin_comment": "testing deny request"
}
**Response Body:**
{
  "id": 3,
  "admin_comment": "denial reason is : testing deny request",
  "admin_timestamp": "2017-02-03T04:41:57Z",
  "admin": 1
}
**PATCH: /api/request/cancel/{pk}/**
Note: status field of request is updated automatically on backend
**Request Body:**
{
	"id" : 4,
	"reason": "testing cancellation"
}
**Response Body:**
{
  "id": 4,
  "reason": "testing create request for nexus cancellation reason is : testing cancellation"
}
