### ISSUE TITLE
Update models in Log

### ISSUE THREAD

**Issue by nesh170** [nesh170/asap-inventory-system#82]

**Comment by nesh170** [comment]
Model:-

Log

 - auth.User initiating_user (Foreign Key to auth.user) 
 - Action nature (Foreign Key to action)
 - Timestamp timestamp (auto_now=True)
 - auth.User effected_user(Foreign Key to auth.user) [Not Required]

Action

 - String color (unique)
 - String action_name (unique)

ItemLog

 - Log log (Foreign Key to Log)
 - Item item (Foreign Key to Item)

**Comment by ankitkayastha** [comment]
https://github.com/nesh170/asap-inventory-system/pull/122
